# https://travis-ci.org/jakubroztocil/django-settings-export
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - pypy3
env:
  - DJANGO=Django==1.11
  - DJANGO=Django==2.1
  - DJANGO=Django

matrix:
  exclude:

    ### Django>=2.0 doesn't support Python 2
    - python: 2.7
      env: DJANGO=Django==2.1
    - python: 2.7
      env: DJANGO=Django
    - python: pypy
      env: DJANGO=Django==2.1
    - python: pypy
      env: DJANGO=Django

script:
  - pip install $DJANGO coverage
  - pip install .
  - coverage run --source=. --omit=setup.py ./tests/manage.py test --verbosity=2
after_success:
  - pip install python-coveralls
  - coveralls
